### ISSUE TITLE
[QUESTION] Support all features without workarrounds?

### ISSUE THREAD

**Issue by shawe** [Eihen/JasperPHP#3]
I'm trying cossou/jasperphp v2.5, and seems to need some workarrounds in any features:

Some hack to JasperReport datasource is required. You need to indicate datasource expression for each table, list, and subreport.

	<datasetRun subDataset="invoice_details" uuid="a91cc22b-9a3f-45eb-9b35-244890d35fc7">
            <dataSourceExpression>
	       <![CDATA[((net.sf.jasperreports.engine.data.JsonDataSource)$P{REPORT_DATA_SOURCE}).subDataSource("result.details")]]>
	    </dataSourceExpression>
	</datasetRun>

Your library have the same problem?

**Comment by Eihen** [comment]
Neither mine or cossou libraries manipulate the jrxml/jasper file contents, they are only PHP wrappers for the JasperStarter application which in turn relies on the [net.sf.jasperreports](https://mvnrepository.com/artifact/net.sf.jasperreports/jasperreports) java library, for any problems related to how the content of those files are handled you should refer to https://bitbucket.org/cenote/jasperstarter/.
That said, my library supports all the feature that JasperStarter supports.

**Comment by shawe** [comment]
Thanks for your reply. Seems that I'm trying to do is not supported.
